PINK = "#e2979c"
RED = "#e7305b"
GREEN = "#9bdeac"
YELLOW = "#f7f5dd"
FONT_NAME = "Courier"
WORK_MIN = 0.1
SHORT_BREAK_MIN = 0.1
LONG_BREAK_MIN = 0.5
WORK_SESSION = "Work Session"
SHORT_BREAK = "Short Break"
BREAK = "Break"
PAUSE = "Pause"
START = "Start"
RESUME = "Resume"
RESET = "Reset"
PAUSED = "PAUSED"
IDLE = "Idle"
POMODOROS = "Pomodoros"
CHECK_MARK = "✔"